# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ICSOB 2025
email: your-email@example.com
description: The International Conference on Software Business (ICSOB) attracts both researchers and practitioners who are concerned with software-intensive business in different ways, and brings them together to share their findings and experiences from the field of software-intensive business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://icsob2025.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "melegati/jekyll-theme-conference"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-target-blank

target-blank:
  css_class: ext-link

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#comment

sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  - vendor

conference:
  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      img: "favicon.ico{%- for r in d.rooms -%}
  {%- assign t = r.talks | first -%}
  {%- include partials/get_talk_time.html -%}

  {%- if forloop.index == 1 or talk_start_day < day_start_day or talk_start_day == day_start_day and talk_start_hour < day_start_hour or talk_start_hour == day_start_hour and talk_start_min < day_start_min-%}
    {%- assign day_start_talk = t -%}
    {%- assign day_start_day = talk_start_day -%}
    {%- assign day_start_hour = talk_start_hour -%}
    {%- assign day_start_min = talk_start_min -%}
  {%- endif -%}

  {%- assign t = r.talks | last -%}
  {%- include partials/get_talk_time.html -%}

  {%- if forloop.index == 1 or talk_end_day > day_end_day or talk_end_day == day_end_day and talk_end_hour > day_end_hour or talk_end_hour == day_end_hour and talk_end_min > day_end_min-%}
    {%- assign day_end_talk = t -%}
    {%- assign day_end_day = talk_end_day -%}
    {%- assign day_end_hour = talk_end_hour -%}
    {%- assign day_end_min = talk_end_min -%}
  {%- endif -%}
{%- endfor -%}
"
      url: "https://icsob2025.github.io/"
    links:
      - name: Home
        relative_url: /
      - name: Call for Submissions
        menu:
          - name: Research Papers
            relative_url: "/ResearchPapers"
          - name: PhD Retreat
            relative_url: "/PhDRetreatSubmissions"
          - name: Posters and Demos
            relative_url: "/Posters"
          - name: Special Issue
            relative_url: "/specialissue"
          - name: Awards
            relative_url: /Awards/
          - name: Student Volunteers
            relative_url: "/studentvolunteers"
        # - name: Program
          # menu:
          # - name: Program Overview
          # relative_url: /program/
          # - name: Detailed Schedule
          #  relative_url: /Schedule/
          # - name: Keynotes
          #  relative_url: /speakers/
          # - name: Workshop
          #  relative_url: "/workshop"

      - name: Important Dates
        relative_url: /importantdates/

        # - name: Sponsors
        # relative_url: /sponsor/

      - name: Organisation
        menu:
          - name: Organising Committee
            relative_url: /organisation/
          - name: Program Committee
            relative_url: /programCommittee/
        # - name: Attending
          # menu:
            # - name: Registration
            # relative_url: /registration/
            # - name: Location
            # relative_url: /location/



  # Information boxes
  info_bars:
    - title: Welcome to the Conference Theme for Jekyll!
      color: primary
      main_only: true
      text: |
        The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

        ---

        See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.

      pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop: 240 # in minutes
    streaming:
      enable: true
      pause: 60 # in minutes
      prepend: 5 # in minutes
      extend: 5 # in minutes
    demo:
      enable: false
      duration: 300 # in seconds
      pause: 10 # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 48.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17


    # Hide icons on talk overview page
    hide_icons: false


  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: "/location"
    # Main page title shown on location/room navigation bar
    navbar_title: "Location"
    # Show map on location main page
    map: true


    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true


